### ISSUE TITLE
cmake failed by not found gmp

### ISSUE THREAD

**Issue by gipsyh** [stanford-centaur/pono#317]
```
CMake Error at CMakeLists.txt:69 (find_package):
  By not providing "FindGMP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "GMP", but
  CMake did not find one.

  Could not find a package configuration file provided by "GMP" with any of
  the following names:

    GMPConfig.cmake
    gmp-config.cmake

  Add the installation prefix of "GMP" to CMAKE_PREFIX_PATH or set "GMP_DIR"
  to a directory containing one of the above files.  If "GMP" provides a
  separate development package or SDK, be sure it has been installed.
```

Actually, I have install libgmp-dev by apt

**Comment by gipsyh** [comment]
system: ubuntu 23.10

**Comment by CyanoKobalamyne** [comment]
That's strange. This file should be provided by smt-switch. Do you have smt-switch downloaded in the `deps/smt-switch` subfolder? Could you check if the `cmake` folder inside that has the `FindGMP.cmake` file?

**Comment by gipsyh** [comment]
> That's strange. This file should be provided by smt-switch. Do you have smt-switch downloaded in the `deps/smt-switch` subfolder? Could you check if the `cmake` folder inside that has the `FindGMP.cmake` file?

Probelm Solved
Thanks
